/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:3ae5a914-5c03-417b-9e1e-389629b77d0d",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_rlzQLsKDX",
    "aws_user_pools_web_client_id": "7h1u3in8ff5av0tsugn05qnu9k",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "appfacturas991a8-dev",
    "aws_user_files_s3_bucket_region": "eu-west-3",
    "aws_appsync_graphqlEndpoint": "https://v5p5hk6n6ffahajog2dcwks2aa.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
